

/**
* HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 2014년 4월 12일 토요일 오후 10시 17분 30초 KST
*/

public final class RepositeInterface implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.ExtendsOthers value = null;

  public RepositeInterface ()
  {
  }

  public RepositeInterface (HelloApp.ExtendsOthers initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.ORBInterface.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.ORBInterface.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.ORBInterface.type ();
  }

}
